### ISSUE TITLE
test example: bug?

### ISSUE THREAD

**Issue by xiaoyanguoke** [stbraun/fuzzing#2]
![image](https://user-images.githubusercontent.com/15224735/28487238-52f0279c-6ebf-11e7-8f53-b293217ab3c3.png)
![image](https://user-images.githubusercontent.com/15224735/28487251-8ef085f2-6ebf-11e7-91fb-6507dcbed814.png)
![image](https://user-images.githubusercontent.com/15224735/28487257-a5068c60-6ebf-11e7-8ce7-03d99d75c3f5.png)

**Comment by stbraun** [comment]
Could not reproduce this issue.
It may be an issue with Python 2.7 which is not supported by fuzzing.
