### ISSUE TITLE
How to check code coverage?

### ISSUE THREAD

**Issue by CloudApiStudy** [stbraun/fuzzing#3]
Hi, I'm wondering wether this tool is able to get a code coverage report? E.g. for a random function and a set of data generated by `fuzzing.fuzz_string`.

**Comment by stbraun** [comment]
Hi, currently the tool is meant to run programs as independent processes and feed those with fuzzed data. This means a coverage report of the program under test is not possible for this use case.

You may be able to implement a fuzzer with the toolbox which takes a function as described in your post. then you could run coverage for the whole program and extract the data for your function from the resulting report, or you could implement a simple coverage function via sys.settrace. 

Both approaches need some development effort. Currently there is no plan for extensions on my side. But you're free to add such an extension: the sources are under MIT license and can be used freely.

**Comment by CloudApiStudy** [comment]
Thanks so much!
